### ISSUE TITLE
Exchange Constants for Any Magnetic Solid

### ISSUE THREAD

**Issue by hcut** [KAIST-ELST/Jx.jl#6]
Hi,

I wanted to know that I can we calculate the Exchange Constants for Any Magnetic Solid ?
If Yes, then Can we have some more examples regd calculations of J?

**Comment by DHKiem** [comment]
> Hi,
> 
> I wanted to know that I can we calculate the Exchange Constants for Any Magnetic Solid ? If Yes, then Can we have some more examples regd calculations of J?

Thank you for expressing your interest.

If you have obtained the electronic structure solution for your magnetic solid, you can calculate the exchange constants through Jx. I recommend referring to the example of NiO as a guide, accessible here: 
https://kaist-elst.github.io/Jx.jl/docs/
https://kaist-elst.github.io/Jx.jl/docs/example_NiO/

For additional examples of the code in use, you can explore a comprehensive list of publications at
https://kaist-elst.github.io/Jx.jl/publications/

Best regards.
